# Generated by Django 5.0.1 on 2024-01-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
